# <span style="color:red">MY PERSONAL NOTES on Python, NumPy & Vectorization </span>

# Chapter 1: Python vs NumPy (From First Principles)

---

# 🎯 Learning Objectives

By the end of this chapter, you should understand:

- Why NumPy was created.
- Why Python lists are not suitable for Machine Learning.
- How Python stores lists internally.
- How NumPy stores arrays.
- What contiguous memory means.
- Why NumPy is much faster.
- Why every Machine Learning library is built around NumPy.

---

# 1. What is NumPy?

NumPy (**Numerical Python**) is a scientific computing library for Python.

It provides:

- Efficient storage of numerical data
- Fast mathematical operations
- Vectors
- Matrices
- Higher-dimensional arrays
- Linear Algebra operations

Almost every Machine Learning library is built upon NumPy.

Examples:

- TensorFlow
- PyTorch
- Scikit-Learn
- JAX
- OpenCV

---

# 2. Why Was NumPy Created?

Python was designed as a **general-purpose programming language**, not specifically for numerical computation.

Python lists are extremely flexible:

```python
data = [5, "Hello", True, 3.14]
```

A single list can contain different types of objects.

This flexibility makes Python programming easy, but it also makes numerical computation slower.

Machine Learning requires:

- Millions of numbers
- Millions of additions
- Millions of multiplications

Python lists are not optimized for this.

---

# 3. Python Lists Internally

Consider:

```python
a = [5, 7, 10]
```

Most beginners imagine memory as

```
+---+---+----+
| 5 | 7 | 10 |
+---+---+----+
```

This is **NOT** how Python stores a list.

Instead, Python stores **references (addresses)**.

```
List

+--------+--------+--------+
| 1000   | 4200   | 9000   |
+--------+--------+--------+

     ↓         ↓         ↓

 Integer    Integer    Integer
    5          7         10
```

The actual integer objects are scattered across memory.

---

# 4. Problems with Python Lists

## Problem 1: Memory Overhead

Each integer is stored as a complete Python object.

Instead of storing only

```
5
```

Python stores

- Value
- Object Type
- Reference Count
- Metadata

So an integer occupies much more memory than its numerical value alone.

---

## Problem 2: Poor Cache Performance

The CPU prefers reading nearby memory.

Python objects are scattered across RAM.

```
Address 1000

Address 4200

Address 9000
```

The CPU must constantly jump around memory.

This slows execution.

---

## Problem 3: Slow Arithmetic

Suppose

```python
a = [1,2,3]
b = [4,5,6]
```

Python cannot compute

```python
a + b
```

as element-wise addition.

Instead,

```python
a+b
```

produces

```python
[1,2,3,4,5,6]
```

(list concatenation).

To perform element-wise addition, we need a loop:

```python
c = []

for i in range(len(a)):
    c.append(a[i] + b[i])
```

Loops introduce additional overhead.

---

# 5. NumPy's Solution

NumPy is designed specifically for numerical data.

Example

```python
a = np.array([5,7,10])
```

Memory becomes

```
+----+----+----+
| 5  | 7  |10  |
+----+----+----+
```

Everything is stored **contiguously**.

---

# 6. Contiguous Memory

Contiguous means

> Stored one after another in memory.

```
Address

1000
↓

+----+----+----+----+
| 5  | 7  |10  |12  |
+----+----+----+----+
```

Advantages:

- Faster access
- Better cache utilization
- Efficient CPU processing

---

# 7. Why Same Data Type?

NumPy arrays contain only one data type.

Example

```python
np.array([1,2,3])
```

All elements are integers.

Example

```python
np.array([1.0,2.0,3.0])
```

All elements are floating-point numbers.

Why?

Because identical data types allow

- Fixed memory size
- Fast indexing
- Better optimization

---

# 8. What is dtype?

Every NumPy array has a data type.

Example

```python
a.dtype
```

Output

```
int64
```

or

```
float64
```

Meaning

- int → Integer
- float → Floating-point number
- 64 → Uses 64 bits

Since

$$
8\text{ bits}=1\text{ byte}
$$

Then

$$
64\text{ bits}=8\text{ bytes}
$$

---

# Common dtypes

| dtype | Meaning |
|--------|---------|
| int32 | 32-bit Integer |
| int64 | 64-bit Integer |
| float32 | 32-bit Float |
| float64 | 64-bit Float |
| bool | Boolean |

---

# 9. Why Float64?

Machine Learning usually works with decimal numbers.

Example

$$
0.257
$$

$$
-3.81
$$

$$
1.456
$$

Therefore NumPy defaults to

```
float64
```

in many creation functions.

---

# 10. Why NumPy is Faster

Python loops

```python
for i in range(n):
```

are interpreted one instruction at a time.

NumPy operations are implemented in optimized C code.

Example

```python
np.dot(a,b)
```

does **not** perform multiplication using Python loops.

Instead,

Python hands the work to optimized C libraries.

Benefits:

- Faster execution
- Better memory management
- CPU vectorization
- SIMD optimization

---

# 11. Why Machine Learning Uses NumPy

Suppose a dataset contains

- 1,000,000 training examples
- 200 features

Training requires

- Millions of additions
- Millions of multiplications
- Millions of gradient computations

Python loops would be very slow.

NumPy performs these operations efficiently.

---

# 12. Python List vs NumPy Array

| Python List | NumPy Array |
|--------------|-------------|
| General purpose | Numerical computing |
| Different data types | Same data type |
| Stores references | Stores values directly |
| Slower | Faster |
| Uses Python loops | Uses optimized C code |
| Flexible | Memory efficient |

---

# 13. Machine Learning Connection

Throughout Andrew Ng's course,

Training data

$$
X
$$

Weights

$$
w
$$

Bias

$$
b
$$

Predictions

$$
\hat{y}
$$

are all stored using NumPy arrays.

Every algorithm in this specialization depends on NumPy.

---

# Key Takeaways

✅ Python lists are flexible but slow.

✅ NumPy arrays are designed for numerical computation.

✅ NumPy stores data contiguously in memory.

✅ NumPy arrays contain one data type.

✅ NumPy uses optimized C libraries for fast computation.

✅ Every major Machine Learning framework is built on NumPy.

---

# Memory Trick

Think of:

**Python List** 📂

```
Folder of addresses
```

```
Address A

Address B

Address C
```

---

**NumPy Array** 🚆

```
+----+----+----+----+
| 5  | 7  |10  |12  |
+----+----+----+----+
```

Everything is stored together.

This is why NumPy is fast.

---

# Interview Questions

### Q1. Why is NumPy faster than Python lists?

**Answer**

Because NumPy

- stores contiguous memory
- uses homogeneous data types
- is implemented in optimized C
- avoids Python loop overhead

---

### Q2. Why can't Python lists be efficiently used for Machine Learning?

Because

- scattered memory
- higher memory overhead
- slower arithmetic
- no vectorized operations

---

### Q3. Why do ML libraries use NumPy?

Because NumPy provides

- efficient numerical computation
- vectorization
- optimized memory usage
- linear algebra support

---

# Chapter 2: Vectors (From First Principles)

---

# 🎯 Learning Objectives

By the end of this chapter, you should understand:

- What a vector is.
- Why vectors are fundamental in Machine Learning.
- Mathematical notation for vectors.
- Difference between scalars and vectors.
- Python indexing vs mathematical indexing.
- Shape vs Dimension.
- Why `(4,)` contains a comma.
- How NumPy stores vectors.
- Why Andrew Ng uses 1-D arrays.
- How vectors connect to Linear Regression.

---

# 1. What is a Vector?

A **vector** is an **ordered collection of numbers of the same data type**.

Examples

```python
[5, 8, 10]
```

```python
[1200, 3, 15, 8]
```

The **order matters**.

Example

```python
[170, 65, 22]
```

may represent

| Position | Meaning |
|----------|---------|
| 1 | Height (cm) |
| 2 | Weight (kg) |
| 3 | Age (years) |

Changing the order changes the meaning.

---

# 2. Why are Vectors Important in Machine Learning?

Every training example is represented as a vector.

Example

| Feature | Value |
|---------|------:|
| Area | 1200 |
| Bedrooms | 3 |
| Age | 15 |
| Distance | 8 |

Instead of writing

```python
area = 1200
bedrooms = 3
age = 15
distance = 8
```

we simply write

```python
x = [1200,3,15,8]
```

This entire list is one vector.

> **One training example = One feature vector**

---

# 3. Mathematical Notation

Vectors are written using **bold lowercase letters**.

Example

$$
\mathbf{x}
=
\begin{bmatrix}
1200\\
3\\
15\\
8
\end{bmatrix}
$$

Notice

- Bold letters → Vector
- Normal letters → Scalar

Example

| Symbol | Meaning |
|---------|---------|
| $x$ | Scalar (single number) |
| $\mathbf{x}$ | Vector |

---

# 4. Elements of a Vector

Suppose

$$
\mathbf{x}
=
\begin{bmatrix}
1200\\
3\\
15\\
8
\end{bmatrix}
$$

Each value is called an **element**.

Examples

$$
x_1=1200
$$

$$
x_2=3
$$

$$
x_3=15
$$

$$
x_4=8
$$

Andrew later writes

$$
x_j
$$

which means

> the **j-th feature**.

---

# 5. Mathematical Indexing vs Python Indexing

This is one of the most common beginner mistakes.

### Mathematics

Starts counting from **1**.

Example

$$
\mathbf{x}
=
[5,8,10]
$$

Then

$$
x_1=5
$$

$$
x_2=8
$$

$$
x_3=10
$$

---

### Python

Starts counting from **0**.

```python
x=[5,8,10]
```

```python
x[0] = 5
```

```python
x[1] = 8
```

```python
x[2] = 10
```

---

## Comparison

| Mathematics | Python |
|-------------|--------|
| $x_1$ | `x[0]` |
| $x_2$ | `x[1]` |
| $x_3$ | `x[2]` |

---

# 6. What is Dimension?

The word **dimension** has two meanings.

---

## Mathematical Meaning

Dimension means

> Number of elements.

Example

```python
[4,8,2]
```

contains

**3 elements**

Therefore,

its mathematical dimension is

$$
3
$$

---

## NumPy Meaning

NumPy defines dimension differently.

Dimension means

> Number of axes.

Example

```python
a=np.array([1,2,3])
```

Shape

```python
(3,)
```

This is a

**1-dimensional array**

because it has only one axis.

---

# 7. What is Shape?

Shape describes

> How NumPy interprets the stored data.

Example

```python
a=np.array([5,7,9,11])
```

```python
a.shape
```

returns

```python
(4,)
```

Meaning

- One axis
- Four elements

Think of shape as the blueprint of an array.

---

# 8. Why Does `(4,)` Have a Comma?

This confuses many beginners.

```python
(4)
```

is **not** a tuple.

Python treats it as

```python
4
```

To create a tuple with one value, Python requires

```python
(4,)
```

The comma tells Python

> "This is a tuple."

Example

```python
type((4))
```

returns

```python
int
```

Example

```python
type((4,))
```

returns

```python
tuple
```

---

# 9. NumPy Vector Internally

Suppose

```python
a=np.array([10,20,30,40])
```

Memory

```
+----+----+----+----+
|10  |20  |30  |40  |
+----+----+----+----+
```

The variable

```python
a
```

stores only a reference to this memory.

NumPy also stores

- Shape
- Data Type (dtype)
- Number of Dimensions (ndim)

---

# 10. Why Andrew Uses 1-D Arrays

Instead of

```python
w=np.array([[2],[4],[5]])
```

Andrew usually writes

```python
w=np.array([2,4,5])
```

Why?

Because most operations in Course 1 involve

**Vector × Vector**

Example

```python
np.dot(x,w)
```

Both vectors have shape

```python
(n,)
```

making the notation simple.

---

# 11. Vector Creation

Create a vector filled with zeros

```python
np.zeros(4)
```

Output

```python
[0. 0. 0. 0.]
```

---

Generate random values

```python
np.random.rand(4)
```

Example

```python
[0.24 0.61 0.87 0.18]
```

---

Create a vector manually

```python
np.array([5,4,3,2])
```

Output

```python
[5 4 3 2]
```

---

# 12. Why Does NumPy Default to Float?

Notice

```python
np.zeros(4)
```

returns

```python
[0. 0. 0. 0.]
```

instead of

```python
[0 0 0 0]
```

Machine Learning mostly works with decimal numbers.

Therefore,

NumPy often defaults to

```python
float64
```

---

# 13. Visual Representation

```
Index

0    1    2    3

↓

+----+----+----+----+
|10  |20  |30  |40  |
+----+----+----+----+
```

Shape

```python
(4,)
```

Data Type

```python
int64
```

Dimensions

```python
1
```

---

# 14. Machine Learning Connection

Suppose one house has

| Feature | Value |
|---------|------:|
| Area | 1200 |
| Bedrooms | 3 |
| Age | 20 |

Represent it as

```python
x=np.array([1200,3,20])
```

Weights

```python
w=np.array([250,10000,-500])
```

Prediction later becomes

$$
\hat y = \mathbf{w}\cdot\mathbf{x}+b
$$

This simple equation forms the foundation of

- Linear Regression
- Logistic Regression
- Neural Networks

---

# Key Takeaways

✅ A vector is an ordered collection of numbers.

✅ One training example is represented as one feature vector.

✅ Mathematics indexes vectors from **1**.

✅ Python indexes vectors from **0**.

✅ Shape tells NumPy how to interpret memory.

✅ `(4,)` means one-dimensional array with four elements.

✅ NumPy stores vectors contiguously in memory.

✅ Most Machine Learning algorithms operate on vectors.

---

# Memory Trick

Think of a vector as a **student report card**.

```
[90, 85, 78, 95]
```

Each position has a meaning.

| Position | Subject |
|----------|----------|
| 1 | Maths |
| 2 | Physics |
| 3 | Chemistry |
| 4 | English |

Changing the order changes the meaning completely.

---

# Interview Questions

### Q1. What is a vector?

A vector is an ordered collection of values of the same data type.

---

### Q2. What is the difference between a scalar and a vector?

A scalar contains one value.

A vector contains multiple ordered values.

---

### Q3. Why does Python use zero-based indexing?

Because array indexing starts from the memory offset of the first element, which is zero.

---

### Q4. What does `(4,)` mean?

It represents a one-dimensional NumPy array containing four elements.

---

### Q5. Why are vectors used in Machine Learning?

Each training example consists of multiple features, making vectors the natural way to represent data.

---

# Section 1: NumPy ndarray (The Foundation of NumPy)

---

# 🎯 Learning Objectives

After this section, you should understand:

- What an ndarray is
- Why NumPy uses ndarrays instead of Python lists
- Internal properties of an ndarray
- Shape vs Dimension vs Size
- dtype
- itemsize
- nbytes
- Why ndarray is the foundation of Machine Learning

---

# 1. What is an ndarray?

**ndarray** stands for

> **N-Dimensional Array**

It is NumPy's core data structure.

Everything in NumPy is built around the ndarray.

Examples

```python
np.array([1,2,3])          # 1-D ndarray

np.array([[1,2],[3,4]])    # 2-D ndarray

np.array([[[1],[2]]])      # 3-D ndarray
```

---

# 2. Why Was ndarray Created?

Python lists are designed for **general-purpose programming**.

NumPy ndarrays are designed for **high-performance numerical computing**.

Unlike Python lists, ndarrays:

- store homogeneous data
- store data contiguously in memory
- support vectorized operations
- consume less memory
- execute much faster

This is why almost every Machine Learning library uses ndarrays internally.

---

# 3. Properties of an ndarray

Every ndarray stores two things:

### Data

The actual numerical values.

Example

```python
[5,10,15]
```

---

### Metadata

Information describing the array.

Examples

- Shape
- Data type
- Number of dimensions
- Memory usage

The data and metadata together define an ndarray.

---

# 4. Creating an ndarray

```python
import numpy as np

a = np.array([10,20,30,40])
```

The variable `a` now points to an ndarray object.

---

# 5. Important ndarray Attributes

Suppose

```python
a = np.array([[1,2,3],
              [4,5,6]])
```

---

## shape

Describes the size of each axis.

```python
a.shape
```

Output

```python
(2,3)
```

Meaning

- 2 rows
- 3 columns

---

## ndim

Number of dimensions (axes).

```python
a.ndim
```

Output

```python
2
```

---

## size

Total number of elements.

```python
a.size
```

Output

```python
6
```

Because

$$
2 \times 3 = 6
$$

---

## dtype

Data type of every element.

```python
a.dtype
```

Output

```python
int64
```

Possible values

- int32
- int64
- float32
- float64
- bool
- complex128

---

## itemsize

Memory occupied by **one element** (in bytes).

```python
a.itemsize
```

Output

```python
8
```

Meaning

Each integer occupies

$$
8\text{ bytes}
$$

---

## nbytes

Total memory consumed by the array.

```python
a.nbytes
```

Output

```python
48
```

Because

$$
6 \times 8 = 48
$$

---

# 6. Shape vs Dimension vs Size

This is one of the most confusing topics for beginners.

| Property | Meaning | Example |
|----------|---------|----------|
| shape | Length of each axis | `(2,3)` |
| ndim | Number of axes | `2` |
| size | Total elements | `6` |

Example

```python
a=np.array([[1,2,3],
            [4,5,6]])
```

```
Shape  -> (2,3)

ndim   -> 2

size   -> 6
```

---

# 7. Memory Representation

```
Variable

a

↓

+---------------------+
| ndarray object      |
+---------------------+
| shape = (2,3)       |
| dtype = int64       |
| ndim = 2            |
| size = 6            |
| pointer ----------+ |
+-------------------|--+
                    |
                    v

+---+---+---+---+---+---+
| 1 | 2 | 3 | 4 | 5 | 6 |
+---+---+---+---+---+---+
```

Notice that the metadata and the actual numerical values are stored separately.

---

# 8. Why ndarray is Important in Machine Learning

In Andrew Ng's course,

Training data

```python
X
```

Weights

```python
w
```

Bias

```python
b
```

Predictions

```python
y_hat
```

are all stored using ndarrays.

Without ndarrays, vectorized Machine Learning would not be practical.

---

# Quick Revision

| Attribute | Description |
|------------|-------------|
| shape | Size of every axis |
| ndim | Number of dimensions |
| size | Total elements |
| dtype | Data type |
| itemsize | Bytes per element |
| nbytes | Total memory |

---

# Interview Question

**Q. What is the difference between `shape`, `size`, and `ndim`?**

- `shape` → size along each axis
- `ndim` → number of axes
- `size` → total number of elements

---

# Section 2: Creating NumPy Arrays

---

# 🎯 Learning Objectives

In this section, you'll learn how to create NumPy arrays efficiently using the most common creation functions.

We'll cover:

- np.array()
- np.zeros()
- np.ones()
- np.empty()
- np.full()
- np.arange()
- np.linspace()

These functions are used throughout Machine Learning for creating datasets, initializing weights, generating sequences, and preparing matrices.

---

# Overview

| Function | Creates |
|----------|----------|
| `np.array()` | Array from existing data |
| `np.zeros()` | Filled with zeros |
| `np.ones()` | Filled with ones |
| `np.empty()` | Uninitialized array |
| `np.full()` | Filled with one constant value |
| `np.arange()` | Evenly spaced values with a step |
| `np.linspace()` | Evenly spaced values by count |

---

# 1. np.array()

Creates an ndarray from an existing Python object.

## Syntax

```python
np.array(object, dtype=None)
```

---

### 1D Example

```python
a = np.array([1,2,3,4])
```

Output

```python
[1 2 3 4]
```

---

### 2D Example

```python
a = np.array([[1,2],
              [3,4]])
```

Output

```
[[1 2]
 [3 4]]
```

---

### ML Use

- Training datasets
- Feature vectors
- Labels
- Weight vectors

---

# 2. np.zeros()

Creates an array filled with zeros.

Useful for initialization.

## Syntax

```python
np.zeros(shape, dtype=float)
```

---

### 1D

```python
np.zeros(5)
```

```
[0. 0. 0. 0. 0.]
```

---

### 2D

```python
np.zeros((2,3))
```

```
[[0. 0. 0.]
 [0. 0. 0.]]
```

---

### ML Use

Very commonly used to initialize

- weights
- gradients
- accumulators
- buffers

---

# 3. np.ones()

Creates an array filled with ones.

## Syntax

```python
np.ones(shape)
```

---

### 1D

```python
np.ones(4)
```

```
[1. 1. 1. 1.]
```

---

### 2D

```python
np.ones((3,2))
```

```
[[1. 1.]
 [1. 1.]
 [1. 1.]]
```

---

### ML Use

Useful for

- masks
- scaling
- initialization
- testing algorithms

---

# 4. np.empty()

Allocates memory **without initializing values**.

The contents are whatever happened to be in memory.

## Syntax

```python
np.empty(shape)
```

---

### 1D

```python
np.empty(5)
```

Possible output

```
[6.9e-310 0.0 2.3e-308 ...]
```

---

### 2D

```python
np.empty((2,2))
```

Output is unpredictable.

---

### ML Use

Used only when you'll immediately overwrite every value.

Slightly faster than `np.zeros()` because no initialization is performed.

⚠ Never assume the values are zero.

---

# 5. np.full()

Creates an array filled with a specified value.

## Syntax

```python
np.full(shape, fill_value)
```

---

### 1D

```python
np.full(5, 7)
```

```
[7 7 7 7 7]
```

---

### 2D

```python
np.full((2,3), 100)
```

```
[[100 100 100]
 [100 100 100]]
```

---

### ML Use

Useful for

- constant tensors
- placeholder values
- padding

---

# 6. np.arange()

Creates equally spaced values using a fixed step.

## Syntax

```python
np.arange(start, stop, step)
```

`stop` is excluded.

---

### Example

```python
np.arange(2,10,2)
```

```
[2 4 6 8]
```

---

### Float Example

```python
np.arange(0,1,0.2)
```

```
[0.  0.2 0.4 0.6 0.8]
```

---

### ML Use

- indexing
- loops
- plotting
- synthetic datasets

---

# 7. np.linspace()

Creates a specified number of equally spaced values.

Unlike `arange()`, you specify **how many values**, not the step size.

## Syntax

```python
np.linspace(start, stop, num)
```

---

### Example

```python
np.linspace(0,10,5)
```

Output

```
[0. 2.5 5. 7.5 10.]
```

Notice that both endpoints are included by default.

---

### ML Use

- plotting functions
- visualization
- generating continuous feature values

---

# arange() vs linspace()

| arange | linspace |
|---------|-----------|
| Fixed step | Fixed number of values |
| Stop excluded | Stop included (default) |
| May suffer floating-point step issues | Preferred for plotting and continuous ranges |

---

# Summary

| Function | Typical Use |
|----------|-------------|
| `array()` | Convert existing data |
| `zeros()` | Initialize weights |
| `ones()` | Masks / initialization |
| `empty()` | Fast allocation |
| `full()` | Constant arrays |
| `arange()` | Integer sequences |
| `linspace()` | Continuous values for graphs |

---

# Coming Next

The next section covers **Random Number Generation**, including:

- `random_sample()`
- `rand()`
- `random()`
- `randint()`
- `uniform()`
- `normal()`
- `randn()`
- `choice()`
- `seed()`
- `default_rng()`

along with a detailed comparison of `random_sample()` vs `rand()` for both 1D and multi-dimensional arrays.

# Section 3: Random Number Generation

---

# 🎯 Learning Objectives

After this section, you should understand:

- Why randomness is important in Machine Learning
- Uniform vs Normal distributions
- Legacy vs Modern NumPy random APIs
- Difference between `rand()` and `random_sample()`
- How to generate random integers
- How to sample random elements
- Why `seed()` matters
- Why `default_rng()` is recommended today

---

# 1. Why Do We Need Random Numbers?

Machine Learning frequently uses random numbers for:

- Initializing neural network weights
- Splitting train/test datasets
- Random sampling
- Data augmentation
- Monte Carlo simulations
- Random shuffling

Without randomness, many ML algorithms would produce biased or poor results.

---

# 2. NumPy Random Module

All legacy random functions are inside

```python
np.random
```

Example

```python
np.random.rand(3)
```

---

# 3. Uniform Distribution

Many NumPy random functions generate values from a **Uniform Distribution**.

Uniform means

> Every value has an equal probability of being selected.

Range

$$
0 \le x < 1
$$

Examples

```
0.15

0.84

0.39

0.02
```

Every value between 0 and 1 is equally likely.

---

# 4. np.random.random_sample()

Generates random floating-point numbers from a uniform distribution.

## Syntax

```python
np.random.random_sample(size=None)
```

Parameter

| Parameter | Meaning |
|-----------|----------|
| size | Shape of the output array |

---

## 1D Example

```python
np.random.random_sample(5)
```

Output

```
[0.12 0.84 0.33 0.91 0.44]
```

---

## 2D Example

```python
np.random.random_sample((2,3))
```

Output

```
[[0.15 0.73 0.42]
 [0.31 0.80 0.09]]
```

Notice

The shape is passed as **one tuple**.

---

# 5. np.random.rand()

Produces exactly the same type of random numbers.

The difference is only in the function signature.

## Syntax

```python
np.random.rand(d0,d1,...)
```

Instead of a tuple,

each dimension is passed separately.

---

## 1D

```python
np.random.rand(5)
```

---

## 2D

```python
np.random.rand(2,3)
```

---

# 6. random_sample() vs rand()

Both generate

- Uniform random numbers
- Range [0,1)
- float64 arrays

Internally they use the same random generator (legacy API).

The only difference is **how the shape is specified**.

| Feature | random_sample() | rand() |
|----------|----------------|--------|
| Shape argument | Tuple | Separate arguments |
| 1D | `random_sample(5)` | `rand(5)` |
| 2D | `random_sample((2,3))` | `rand(2,3)` |
| Distribution | Uniform | Uniform |
| Output dtype | float64 | float64 |

---

### Correct Usage

```python
np.random.random_sample((3,4))
```

```python
np.random.rand(3,4)
```

---

### Incorrect

```python
np.random.rand((3,4))
```

Error

```
TypeError
```

Why?

Because

```python
rand(*shape)
```

expects separate arguments.

---

# 7. np.random.random()

Another function that generates uniform random floats.

If no size is given,

```python
np.random.random()
```

returns

```
0.63829
```

(single scalar)

If size is provided,

```python
np.random.random((2,2))
```

behaves similarly to

```python
random_sample()
```

---

# 8. np.random.randint()

Generates random integers.

## Syntax

```python
np.random.randint(low, high, size)
```

Upper bound is excluded.

---

### Scalar

```python
np.random.randint(1,10)
```

Possible output

```
7
```

---

### 1D

```python
np.random.randint(0,100,5)
```

```
[54 21 90 11 67]
```

---

### 2D

```python
np.random.randint(0,10,(2,3))
```

```
[[4 2 9]
 [8 0 1]]
```

---

### ML Use

- Random labels
- Mini-batches
- Synthetic datasets

---

# 9. np.random.uniform()

Generates random floating-point numbers within any interval.

## Syntax

```python
np.random.uniform(low, high, size)
```

---

Example

```python
np.random.uniform(-5,5,4)
```

Possible output

```
[-1.2 4.7 0.3 -3.9]
```

---

# 10. np.random.normal()

Generates numbers following a **Normal (Gaussian) Distribution**.

## Syntax

```python
np.random.normal(mean,std,size)
```

---

Example

```python
np.random.normal(0,1,5)
```

Possible output

```
[-0.42
 0.83
 1.11
-1.72
 0.35]
```

---

### ML Use

Widely used for

- Weight initialization
- Noise generation
- Simulations

---

# 11. np.random.randn()

Shortcut for

```python
np.random.normal(0,1,size)
```

Example

```python
np.random.randn(3,2)
```

Produces

```
[[ 0.82 -0.41]
 [-1.23  0.57]
 [ 0.91 -0.18]]
```

---

# 12. np.random.choice()

Randomly selects elements from an array.

Example

```python
np.random.choice([10,20,30,40],3)
```

Possible output

```
[40 20 10]
```

---

### ML Use

- Bootstrap sampling
- Random mini-batches
- Random feature selection

---

# 13. np.random.seed()

Sets the starting state of the random number generator.

Example

```python
np.random.seed(42)
```

Now every run produces identical random numbers.

Useful for

- Reproducible experiments
- Debugging
- Research papers

---

# 14. Modern API — default_rng()

Since NumPy 1.17,

the recommended approach is

```python
rng = np.random.default_rng()
```

Then

```python
rng.random((2,3))

rng.integers(0,10,(2,3))

rng.normal(0,1,5)
```

Advantages

- Better random algorithms
- Independent generators
- Thread-safe
- Recommended for new projects

Andrew's notebooks use the older API because it is simpler for beginners.

---

# Summary

| Function | Output |
|----------|---------|
| random_sample() | Uniform floats |
| rand() | Uniform floats |
| random() | Uniform floats |
| randint() | Random integers |
| uniform() | Uniform interval |
| normal() | Gaussian numbers |
| randn() | Standard normal |
| choice() | Random sampling |
| seed() | Reproducibility |
| default_rng() | Modern generator |

---

# Section 4: Array Properties and Memory

---

# 🎯 Learning Objectives

In this section you'll learn:

- shape
- ndim
- size
- dtype
- itemsize
- nbytes
- astype()
- copy()
- view()
- Why NumPy arrays are memory efficient

---

# 1. Why Array Properties Matter

A NumPy array is more than just numbers.

Every array stores

- data
- metadata

Metadata tells NumPy how to interpret the stored values.

---

# Example Array

```python
a = np.array([[1,2,3],
              [4,5,6]])
```

```
Shape

↓

(2,3)

Rows

↓

2

Columns

↓

3
```

---

# 2. shape

Returns the size of each axis.

```python
a.shape
```

Output

```python
(2,3)
```

---

### 1D

```python
np.array([1,2,3]).shape

(3,)
```

---

### 2D

```python
np.array([[1,2],[3,4]]).shape

(2,2)
```

---

# 3. ndim

Number of dimensions.

```python
a.ndim
```

Output

```
2
```

Examples

| Array | ndim |
|---------|------|
| `[1,2,3]` | 1 |
| `[[1,2],[3,4]]` | 2 |
| `[[[1]]]` | 3 |

---

# 4. size

Total number of elements.

```python
a.size
```

Output

```
6
```

Formula

$$
\text{size}= \prod \text{shape}
$$

---

# 5. dtype

Type of every element.

```python
a.dtype
```

Possible outputs

```
int64

float64

bool
```

---

# 6. astype()

Converts data type.

Example

```python
a.astype(float)
```

Output

```
[1. 2. 3.]
```

Original array remains unchanged.

---

# 7. itemsize

Memory used by one element.

```python
a.itemsize
```

Output

```
8
```

Meaning

Each element occupies

```
8 bytes
```

---

# 8. nbytes

Total memory used.

```python
a.nbytes
```

Formula

```
size × itemsize
```

---

Example

```
6 × 8

=

48 bytes
```

---

# 9. copy()

Creates an independent copy.

```python
b = a.copy()
```

Changing

```python
b
```

does **not** affect

```python
a
```

---

# 10. view()

Creates another view of the same memory.

```python
b = a.view()
```

Changing

```python
b
```

also changes

```python
a
```

because both reference the same data.

---

# copy() vs view()

| copy() | view() |
|----------|---------|
| New memory | Shared memory |
| Independent | Linked |
| More memory | Less memory |
| Safer | Faster |

---

# 11. Why NumPy is Memory Efficient

Python list

```
list

↓

references

↓

objects
```

NumPy

```
array

↓

contiguous values
```

Advantages

- Faster access
- Better CPU cache utilization
- Less memory
- SIMD optimization

---

# 12. Quick Reference

| Attribute | Description |
|-----------|-------------|
| shape | Length of each axis |
| ndim | Number of axes |
| size | Total elements |
| dtype | Data type |
| itemsize | Bytes per element |
| nbytes | Total bytes |

---

# ML Connection

When training a neural network,

checking

```python
X.shape

w.shape

y.shape
```

is often the **first debugging step**.

Many ML errors occur because array shapes are incompatible.

Always inspect the shape before performing mathematical operations.

---

# Section 5: Indexing & Slicing

---

# 🎯 Learning Objectives

After this section, you should understand:

- Indexing
- Negative indexing
- Slicing
- Fancy indexing
- Boolean indexing
- Views vs Copies
- 1D and 2D indexing
- Common mistakes

---

# 1. What is Indexing?

**Indexing** means accessing one or more elements of an array using their position.

Python uses **zero-based indexing**.

Example

```python
a = np.array([10,20,30,40])
```

```
Index

0    1    2    3

↓

10   20   30   40
```

---

# 2. Accessing Elements

## 1D

```python
a[0]
```

```
10
```

```python
a[2]
```

```
30
```

---

## 2D

```python
A = np.array([[1,2,3],
              [4,5,6]])
```

```
      Column

        0 1 2

Row 0   1 2 3

Row 1   4 5 6
```

Access

```python
A[1,2]
```

Output

```
6
```

General form

```python
A[row, column]
```

---

# 3. Negative Indexing

Negative indices count from the end.

```python
a = np.array([10,20,30,40])
```

```python
a[-1]
```

```
40
```

```python
a[-2]
```

```
30
```

Useful when the array length is unknown.

---

# 4. What is Slicing?

Slicing extracts a portion of an array.

General syntax

```python
array[start:stop:step]
```

where

| Parameter | Meaning |
|------------|----------|
| start | Starting index (inclusive) |
| stop | Ending index (exclusive) |
| step | Interval between elements |

---

# 5. Why is stop Excluded?

Python uses

$$
[start,\;stop)
$$

This notation means

- Start is included.
- Stop is excluded.

Example

```python
a = np.arange(10)
```

```python
a[2:6]
```

Output

```
[2 3 4 5]
```

Notice

```
6
```

is not included.

---

# 6. Common Slicing Examples

```python
a = np.arange(10)
```

### First three elements

```python
a[:3]
```

```
[0 1 2]
```

---

### Elements after index 3

```python
a[3:]
```

```
[3 4 5 6 7 8 9]
```

---

### Every second element

```python
a[::2]
```

```
[0 2 4 6 8]
```

---

### Reverse

```python
a[::-1]
```

```
[9 8 7 6 5 4 3 2 1 0]
```

---

# 7. 2D Slicing

Suppose

```python
A = np.arange(12).reshape(3,4)
```

```
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
```

---

### Entire row

```python
A[1]
```

or

```python
A[1,:]
```

Output

```
[4 5 6 7]
```

---

### Entire column

```python
A[:,2]
```

Output

```
[2 6 10]
```

---

### Submatrix

```python
A[0:2,1:3]
```

Output

```
[[1 2]
 [5 6]]
```

---

# 8. Fancy Indexing

Instead of one index,

provide multiple indices.

```python
a = np.array([10,20,30,40,50])
```

```python
a[[0,2,4]]
```

Output

```
[10 30 50]
```

Useful when selecting arbitrary elements.

---

# 9. Boolean Indexing

Select elements satisfying a condition.

```python
a = np.array([4,7,2,9,5])
```

```python
a[a>5]
```

Output

```
[7 9]
```

Another example

```python
a[a%2==0]
```

Output

```
[4 2]
```

This is heavily used in data preprocessing.

---

# 10. Views vs Copies

One of NumPy's most important concepts.

Example

```python
a=np.array([1,2,3,4])

b=a[1:3]
```

Does NumPy create new memory?

No.

It creates a **view**.

```
a

↓

1 2 3 4

    ↑ ↑

    b
```

Changing

```python
b[0]=100
```

also changes

```python
a
```

Output

```
a

[1 100 3 4]
```

---

# 11. Creating an Actual Copy

```python
b=a[1:3].copy()
```

Now

```python
b
```

has independent memory.

Changing

```python
b
```

does not change

```python
a
```

---

# 12. Quick Revision

| Operation | Example |
|-----------|----------|
| Index | `a[2]` |
| Slice | `a[2:6]` |
| Reverse | `a[::-1]` |
| Row | `A[1,:]` |
| Column | `A[:,2]` |
| Fancy Index | `a[[1,4]]` |
| Boolean Index | `a[a>5]` |

---

# ML Connection

Suppose

```python
X
```

contains 1000 training examples.

Extract one example

```python
X[25]
```

Extract one feature

```python
X[:,0]
```

Extract first 100 samples

```python
X[:100]
```

These indexing operations appear throughout Andrew Ng's assignments.

---

# Section 6: Vectorized Operations

---

# 🎯 Learning Objectives

After this section, you should understand:

- Element-wise operations
- Scalar operations
- Universal Functions (ufuncs)
- Broadcasting
- Dot Product
- Matrix Multiplication
- Why vectorization is much faster than Python loops

---

# 1. What is Vectorization?

Vectorization means

> Performing operations on an entire array at once instead of using explicit Python loops.

Instead of

```python
for i in range(len(a)):
    c[i]=a[i]+b[i]
```

write

```python
c=a+b
```

NumPy performs the loop internally using optimized C code.

---

# 2. Element-wise Operations

Suppose

```python
a=np.array([1,2,3])

b=np.array([4,5,6])
```

Addition

```python
a+b
```

```
[5 7 9]
```

Subtraction

```python
a-b
```

```
[-3 -3 -3]
```

Multiplication

```python
a*b
```

```
[4 10 18]
```

Division

```python
a/b
```

```
[0.25 0.40 0.50]
```

Each operation is performed element by element.

---

# 3. Scalar Operations

A scalar is a single number.

Example

```python
a=np.array([1,2,3])
```

```python
a+5
```

```
[6 7 8]
```

```python
a*10
```

```
[10 20 30]
```

The scalar is automatically applied to every element.

---

# 4. Universal Functions (ufuncs)

NumPy provides optimized mathematical functions.

Example

```python
np.sqrt(a)
```

```python
np.exp(a)
```

```python
np.log(a)
```

```python
np.sin(a)
```

```python
np.cos(a)
```

Example

```python
np.sqrt(np.array([1,4,9]))
```

Output

```
[1. 2. 3.]
```

---

# 5. Aggregate Functions

Return a single value.

Example

```python
np.sum(a)
```

```python
np.mean(a)
```

```python
np.max(a)
```

```python
np.min(a)
```

```python
np.std(a)
```

```python
np.var(a)
```

---

# 6. Broadcasting

Broadcasting allows arrays of different shapes to work together.

Example

```python
a=np.array([1,2,3])

a+10
```

Output

```
[11 12 13]
```

NumPy behaves as if

```
10

↓

[10 10 10]
```

even though it never creates that array.

---

### Matrix Broadcasting

```python
A=np.array([[1,2],
            [3,4]])

A+10
```

Output

```
[[11 12]
 [13 14]]
```

---

# 7. Dot Product

The most important operation in Machine Learning.

Formula

$$
\mathbf{a}\cdot\mathbf{b}
=
\sum_{i=1}^{n}a_ib_i
$$

Example

```python
a=np.array([1,2,3])

b=np.array([4,5,6])

np.dot(a,b)
```

Computation

$$
1\times4
+
2\times5
+
3\times6
=
32
$$

Output

```
32
```

---

# 8. Matrix Multiplication

NumPy supports

```python
A@B
```

or

```python
np.matmul(A,B)
```

Example

```python
A@B
```

is **not** the same as

```python
A*B
```

| Operator | Meaning |
|-----------|----------|
| `*` | Element-wise multiplication |
| `@` | Matrix multiplication |

---

# 9. Why Vectorization is Faster

Python loop

```
Python

↓

Loop

↓

Interpreter

↓

One operation at a time
```

NumPy

```
Python

↓

Optimized C

↓

SIMD

↓

Parallel CPU instructions
```

Result

Often

10×–100× faster

or even more for very large arrays.

---

# 10. Common ML Operations

Prediction

```python
np.dot(X,w)
```

Gradient

```python
w-alpha*gradient
```

Normalization

```python
(X-mean)/std
```

Activation

```python
np.exp()
```

Loss

```python
np.sum()
```

These operations rely heavily on vectorization.

---

# Quick Revision

| Function | Purpose |
|----------|----------|
| `+,-,*,/` | Element-wise operations |
| `np.sqrt()` | Square root |
| `np.exp()` | Exponential |
| `np.log()` | Natural logarithm |
| `np.sum()` | Sum |
| `np.mean()` | Mean |
| `np.max()` | Maximum |
| `np.dot()` | Dot product |
| `@` | Matrix multiplication |

---

# Interview Questions

### Q1. What is vectorization?

Performing operations on entire arrays without explicit Python loops.

---

### Q2. Why is NumPy vectorization faster?

Because computations are delegated to optimized compiled code that can leverage CPU features such as SIMD and efficient memory access.

---

### Q3. What is the difference between `*` and `@`?

`*` performs element-wise multiplication.

`@` performs matrix multiplication.

---

# ML Connection

Every algorithm in Andrew Ng's course eventually becomes a sequence of vectorized operations.

Learning vectorization well will make Linear Regression, Logistic Regression, Neural Networks, and Deep Learning code much simpler and faster.

# Section 7: Dot Product & Matrix Multiplication

---

# 🎯 Learning Objectives

After completing this section, you should understand:

- What a dot product is
- Geometric meaning of the dot product
- Algebraic meaning of the dot product
- How `np.dot()` works
- Difference between `dot()`, `@`, and `matmul()`
- Inner product vs Outer product
- Element-wise multiplication vs Matrix multiplication
- Shape compatibility rules
- Why the dot product is fundamental to Machine Learning

---

# 1. Why is the Dot Product Important?

The **dot product** is one of the most fundamental operations in Machine Learning.

It is used in:

- Linear Regression
- Logistic Regression
- Neural Networks
- Deep Learning
- Recommendation Systems
- Transformers
- Computer Vision

Almost every prediction in ML begins with a dot product.

Example

$$
\hat{y}=\mathbf{w}\cdot\mathbf{x}+b
$$

where

- $\mathbf{x}$ = input features
- $\mathbf{w}$ = learned weights
- $b$ = bias

---

# 2. What is a Dot Product?

The dot product combines two vectors into **one scalar value**.

Suppose

$$
\mathbf{a}=
\begin{bmatrix}
a_1\\
a_2\\
a_3
\end{bmatrix}
,
\qquad
\mathbf{b}=
\begin{bmatrix}
b_1\\
b_2\\
b_3
\end{bmatrix}
$$

Then

$$
\mathbf{a}\cdot\mathbf{b}
=
a_1b_1+a_2b_2+a_3b_3
$$

The process is simple:

1. Multiply corresponding elements.
2. Add all the products.
3. Return a single number.

---

# 3. Example

```python
a = np.array([1,2,3])

b = np.array([4,5,6])
```

Element-wise multiplication

```
1×4 = 4

2×5 = 10

3×6 = 18
```

Now sum them

```
4+10+18=32
```

Therefore

```python
np.dot(a,b)
```

returns

```
32
```

---

# 4. Visual Representation

```
Vector A

[1   2   3]

×

Vector B

[4   5   6]

↓

Multiply

[4 10 18]

↓

Sum

32
```

Notice

The output is

```
One scalar
```

---

# 5. Implementing Dot Product Manually

```python
def my_dot(a,b):

    result=0

    for i in range(len(a)):
        result += a[i]*b[i]

    return result
```

NumPy does the same operation internally,

but much faster using optimized C code.

---

# 6. Using np.dot()

```python
a=np.array([1,2,3])

b=np.array([4,5,6])

np.dot(a,b)
```

Output

```
32
```

NumPy automatically performs

- multiplication
- summation

in one optimized operation.

---

# 7. Shape Requirement

The two vectors must have the same length.

Correct

```python
(3,)

(3,)
```

Incorrect

```python
(3,)

(4,)
```

This produces

```
ValueError
```

because corresponding elements cannot be matched.

---

# 8. Dot Product in Machine Learning

Suppose

House Features

```
Area

Bedrooms

Age
```

Input vector

```python
x=np.array([1200,3,20])
```

Weights

```python
w=np.array([250,10000,-500])
```

Prediction

```python
np.dot(x,w)
```

Computation

```
1200×250

+

3×10000

+

20×(-500)
```

Every Linear Regression model performs exactly this computation before adding the bias.

---

# 9. Geometric Meaning

The dot product also measures how closely two vectors point in the same direction.

Formula

$$
\mathbf{a}\cdot\mathbf{b}
=
||a||\,||b||\cos\theta
$$

where

- $||a||$ = magnitude of vector $a$
- $||b||$ = magnitude of vector $b$
- $\theta$ = angle between them

Interpretation

| Angle | Dot Product |
|--------|-------------|
| 0° | Maximum positive |
| 90° | Zero |
| 180° | Maximum negative |

This idea becomes important in cosine similarity and recommendation systems.

---

# 10. Element-wise Multiplication vs Dot Product

Suppose

```python
a=np.array([1,2,3])

b=np.array([4,5,6])
```

Element-wise

```python
a*b
```

Output

```
[4 10 18]
```

Dot Product

```python
np.dot(a,b)
```

Output

```
32
```

Difference

| Operation | Output |
|-----------|---------|
| `*` | Vector |
| `np.dot()` | Scalar |

---

# 11. Matrix Multiplication

Suppose

```python
A=np.array([[1,2],
            [3,4]])

B=np.array([[5,6],
            [7,8]])
```

Use

```python
A @ B
```

or

```python
np.matmul(A,B)
```

Output

```
[[19 22]

 [43 50]]
```

Notice

This is **NOT**

element-wise multiplication.

---

# 12. Matrix Multiplication Rule

If

```
A

↓

(m×n)
```

and

```
B

↓

(n×p)
```

Then

```
A@B

↓

(m×p)
```

The **inner dimensions must match**.

Example

```
(3×4)

@

(4×2)

↓

(3×2)
```

Valid

---

Example

```
(3×4)

@

(2×5)
```

Invalid

because

```
4≠2
```

---

# 13. np.dot() vs @ vs np.matmul()

For most Machine Learning code,

```python
A@B
```

and

```python
np.matmul(A,B)
```

behave the same.

| Function | Purpose |
|----------|----------|
| `np.dot()` | Dot product / matrix multiplication (depends on input dimensions) |
| `@` | Matrix multiplication operator |
| `np.matmul()` | Explicit matrix multiplication |

For 1-D vectors,

all produce the same result.

---

# 14. Inner Product vs Outer Product

## Inner Product

Produces

```
One number
```

Example

```python
np.dot(a,b)
```

Output

```
32
```

---

## Outer Product

Produces

```
Matrix
```

Example

```python
np.outer(a,b)
```

Output

```
[[ 4  5  6]

 [ 8 10 12]

 [12 15 18]]
```

Each row is one element of

```
a
```

multiplied by the entire vector

```
b
```

---

# 15. Common Mistakes

### Mistake 1

Using

```python
*
```

when matrix multiplication is intended.

Wrong

```python
A*B
```

Correct

```python
A@B
```

---

### Mistake 2

Mismatched shapes

Always check

```python
A.shape

B.shape
```

before multiplication.

---

### Mistake 3

Confusing vectors and matrices.

Remember

```
(3,)
```

and

```
(3,1)
```

are **different shapes**.

---

# 16. Performance

Manual implementation

```python
for i in range(n):
```

Time Complexity

$$
O(n)
$$

NumPy also performs

$$
O(n)
$$

operations,

but it is much faster because it uses

- optimized C code
- SIMD instructions
- cache-friendly memory layout
- BLAS libraries

---

# Summary

| Operation | Output |
|-----------|---------|
| `a*b` | Element-wise multiplication |
| `np.dot(a,b)` | Dot product |
| `A@B` | Matrix multiplication |
| `np.matmul(A,B)` | Matrix multiplication |
| `np.outer(a,b)` | Outer product |

---

# Interview Questions

### Q1. What is the dot product?

The dot product multiplies corresponding elements of two vectors and sums the products to produce a scalar.

---

### Q2. Why is the dot product important in Machine Learning?

Because predictions in models such as Linear Regression, Logistic Regression, and Neural Networks are computed using the dot product between feature vectors and weight vectors.

---

### Q3. What is the difference between `*` and `@`?

`*` performs element-wise multiplication.

`@` performs matrix multiplication.

---

### Q4. What shape rule must be satisfied for matrix multiplication?

If

$$
A\in\mathbb{R}^{m\times n}
$$

and

$$
B\in\mathbb{R}^{n\times p}
$$

then

$$
A@B
$$

is valid and produces a matrix of shape

$$
(m,p)
$$

The inner dimensions must match.

---

# ML Connection

Almost every supervised learning algorithm computes

$$
\hat y=\mathbf{w}\cdot\mathbf{x}+b
$$

Learning how the dot product works is essential because this single operation forms the mathematical foundation of Linear Regression, Logistic Regression, Neural Networks, Support Vector Machines, and many modern Deep Learning models.

---

# Section 8: Reshaping & Array Manipulation

---

# 🎯 Learning Objectives

After completing this section, you should understand:

- Why reshaping is needed
- `reshape()`
- `flatten()`
- `ravel()`
- `transpose()` / `.T`
- `expand_dims()`
- `squeeze()`
- `concatenate()`
- `stack()`
- `hstack()`
- `vstack()`
- `split()`
- Common shape mistakes
- ML applications of each function

---

# 1. Why Reshape Arrays?

Different Machine Learning algorithms expect data in different shapes.

For example,

Suppose you have

```python
a = np.array([1,2,3,4,5,6])
```

Shape

```python
(6,)
```

Sometimes you need

```
[[1 2 3]
 [4 5 6]]
```

Shape

```python
(2,3)
```

The **data remains the same**, only its arrangement changes.

---

# 2. reshape()

Changes the shape of an array **without changing its data**.

## Syntax

```python
array.reshape(new_shape)
```

The total number of elements **must remain the same**.

---

### Example

```python
a = np.arange(6)
```

```
[0 1 2 3 4 5]
```

```python
a.reshape(2,3)
```

Output

```
[[0 1 2]

 [3 4 5]]
```

---

### Another Example

```python
a.reshape(3,2)
```

Output

```
[[0 1]

 [2 3]

 [4 5]]
```

---

# 3. Using -1 in reshape()

NumPy can automatically calculate one dimension.

Example

```python
a.reshape(-1,2)
```

Output

```
[[0 1]

 [2 3]

 [4 5]]
```

NumPy computes

```
Rows

↓

3
```

because

$$
6 \div 2 = 3
$$

Another example

```python
a.reshape(2,-1)
```

Output

```
[[0 1 2]

 [3 4 5]]
```

---

# 4. Common reshape() Error

Wrong

```python
a.reshape(4,2)
```

Error

```
ValueError
```

Reason

```
Original

6 elements

↓

Requested

8 elements
```

Reshape never creates or removes data.

---

# 5. flatten()

Converts any array into a **1-D copy**.

Example

```python
A = np.array([[1,2],
              [3,4]])
```

```python
A.flatten()
```

Output

```
[1 2 3 4]
```

Changes made to the flattened array **do not affect** the original array.

---

# 6. ravel()

Also converts an array into 1-D.

Example

```python
A.ravel()
```

Output

```
[1 2 3 4]
```

Unlike `flatten()`, `ravel()` **tries to return a view** instead of creating a copy.

---

# flatten() vs ravel()

| flatten() | ravel() |
|------------|---------|
| Returns a copy | Returns a view when possible |
| More memory | More efficient |
| Original unchanged | May share memory |

---

# 7. transpose()

Swaps rows and columns.

Example

```python
A = np.array([[1,2,3],
              [4,5,6]])
```

Shape

```
(2,3)
```

Transpose

```python
A.T
```

Output

```
[[1 4]

 [2 5]

 [3 6]]
```

Shape

```
(3,2)
```

---

# 8. np.transpose()

Equivalent to

```python
A.T
```

```python
np.transpose(A)
```

Useful when working with higher-dimensional arrays.

---

# 9. expand_dims()

Adds a new axis.

Example

```python
a = np.array([1,2,3])
```

Shape

```
(3,)
```

```python
np.expand_dims(a,axis=0)
```

Shape

```
(1,3)
```

Output

```
[[1 2 3]]
```

---

Another example

```python
np.expand_dims(a,axis=1)
```

Shape

```
(3,1)
```

Output

```
[[1]

 [2]

 [3]]
```

---

# 10. squeeze()

Removes dimensions of size 1.

Example

```python
A=np.array([[[5]]])
```

Shape

```
(1,1,1)
```

```python
np.squeeze(A)
```

Output

```
5
```

Shape

```
()
```

Very useful after model predictions.

---

# 11. concatenate()

Joins arrays along an existing axis.

Example

```python
a=np.array([1,2])

b=np.array([3,4])
```

```python
np.concatenate((a,b))
```

Output

```
[1 2 3 4]
```

---

### 2D Example

```python
A=np.array([[1,2]])

B=np.array([[3,4]])
```

```python
np.concatenate((A,B),axis=0)
```

Output

```
[[1 2]

 [3 4]]
```

---

# 12. stack()

Joins arrays by creating a **new axis**.

Example

```python
a=np.array([1,2])

b=np.array([3,4])
```

```python
np.stack((a,b))
```

Output

```
[[1 2]

 [3 4]]
```

Notice

A new dimension is created.

---

# concatenate() vs stack()

| concatenate() | stack() |
|---------------|---------|
| Existing axis | New axis |
| Shape usually unchanged | Shape gains one dimension |

---

# 13. hstack()

Horizontal stack.

```python
np.hstack((a,b))
```

Output

```
[1 2 3 4]
```

For matrices,

joins columns.

---

# 14. vstack()

Vertical stack.

```python
np.vstack((a,b))
```

Output

```
[[1 2]

 [3 4]]
```

For matrices,

joins rows.

---

# hstack() vs vstack()

| Function | Joins |
|-----------|-------|
| hstack() | Columns |
| vstack() | Rows |

---

# 15. split()

Splits arrays into smaller arrays.

Example

```python
a=np.arange(8)
```

```python
np.split(a,4)
```

Output

```
[array([0,1]),

 array([2,3]),

 array([4,5]),

 array([6,7])]
```

---

# 16. hsplit()

Splits columns.

Example

```python
A=np.arange(8).reshape(2,4)
```

```python
np.hsplit(A,2)
```

Output

```
[[0 1]

 [4 5]]

[[2 3]

 [6 7]]
```

---

# 17. vsplit()

Splits rows.

Example

```python
np.vsplit(A,2)
```

Output

```
[[0 1 2 3]]

[[4 5 6 7]]
```

---

# 18. Shape Conversion Summary

```
(6,)

↓

reshape(2,3)

↓

(2,3)

↓

.T

↓

(3,2)

↓

flatten()

↓

(6,)
```

---

# 19. Common Mistakes

### Mistake 1

Forgetting that

```
(3,)
```

and

```
(3,1)
```

are different.

---

### Mistake 2

Using reshape with incompatible sizes.

Always verify

```python
array.size
```

before reshaping.

---

### Mistake 3

Assuming `flatten()` and `ravel()` behave identically.

Remember

- `flatten()` → Copy
- `ravel()` → View (when possible)

---

### Mistake 4

Using `stack()` when `concatenate()` is needed.

Remember

```
stack

↓

new dimension

concatenate

↓

same dimension
```

---

# 20. Machine Learning Applications

### reshape()

Preparing datasets for models

```python
X.reshape(m,n)
```

---

### transpose()

Converting between

```
Samples × Features

↓

Features × Samples
```

---

### flatten()

Flattening images

```
28×28

↓

784
```

before feeding into a model.

---

### concatenate()

Combining datasets.

---

### stack()

Creating mini-batches.

---

### squeeze()

Removing unnecessary dimensions after prediction.

---

# Quick Revision

| Function | Purpose |
|-----------|---------|
| reshape() | Change shape |
| flatten() | 1-D copy |
| ravel() | 1-D view |
| T | Transpose |
| transpose() | Transpose |
| expand_dims() | Add axis |
| squeeze() | Remove axis |
| concatenate() | Join existing axis |
| stack() | Join using new axis |
| hstack() | Join columns |
| vstack() | Join rows |
| split() | Split array |
| hsplit() | Split columns |
| vsplit() | Split rows |

---

# Interview Questions

### Q1. What is the difference between reshape() and transpose()?

- `reshape()` changes the arrangement of elements while preserving their order.
- `transpose()` swaps the axes of an array (e.g., rows become columns).

---

### Q2. What is the difference between flatten() and ravel()?

- `flatten()` always returns a **copy**.
- `ravel()` returns a **view whenever possible**, making it more memory-efficient.

---

### Q3. What is the difference between concatenate() and stack()?

- `concatenate()` joins arrays **along an existing axis**.
- `stack()` joins arrays by **creating a new axis**, increasing the number of dimensions.

---

### Q4. Why is reshape() important in Machine Learning?

Different ML algorithms expect inputs in specific shapes. `reshape()` lets you reorganize data into the required format without changing the underlying values.

---

# ML Connection

Data preparation is a major part of every Machine Learning workflow. Before training a model, you'll frequently need to reshape feature matrices, transpose arrays, flatten images, concatenate datasets, or add/remove dimensions.

Mastering these operations makes it much easier to work with NumPy, pandas, TensorFlow, PyTorch, and scikit-learn, as they all rely heavily on the same array-manipulation concepts.

---